In [66]:
import torch
import numpy as np
import time
from torch.nn import functional as F
device = torch.device("mps")
print(device)

mps


In [2]:
randint = torch.randint(-100,100,(6,))
randint

tensor([ 20, -34,  38, -77,  97, -76])

In [5]:
tensor = torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [6]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [11]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [12]:
logspace = torch.logspace(start=-10, end=10,steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [13]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
a = torch.empty((2,3),dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

## Use GPU

In [21]:
start_time = time.time()
#matrix operations here
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00076222


In [24]:
torch_rand1 = torch.rand(10000,10000).to(device)
torch_rand2 = torch.rand(10000,10000).to(device)

np_rand1 = torch.rand(10000,10000)
np_rand2 = torch.rand(10000,10000)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


0.00638914
0.04571271


In [29]:
%%time
torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)

np_rand1 = torch.rand(100,100,100,100)
np_rand2 = torch.rand(100,100,100,100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


0.00615382
0.03660679
CPU times: user 1.04 s, sys: 189 ms, total: 1.23 s
Wall time: 1.23 s


In [35]:
#Define a probability tensor
probabilities = torch.tensor([0.1,0.9])
#10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
#Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities,num_samples=10,replacement=True)
print(samples)

tensor([0, 0, 1, 1, 1, 1, 1, 1, 1, 1])


In [36]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor,torch.tensor([5])),dim=0)
out

tensor([1, 2, 3, 4, 5])

In [37]:
out = torch.tril(torch.ones(5,5))
out


tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [38]:
out = torch.triu(torch.ones(5,5))
out


tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [39]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [40]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [42]:
torch.exp(torch.tensor([1]))

tensor([2.7183])

In [44]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [45]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked_tensor = torch.stack([tensor1,tensor2,tensor3])
stacked_tensor


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [47]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias=False)
print(linear(sample))

tensor([-7.4413,  3.6386, -3.7612], grad_fn=<SqueezeBackward4>)


In [49]:
import torch.nn.functional as F

#Create a tensor
tensor1 = torch.tensor([1.0,2.0,3.0])

#Apply softmax using torch.nn.functional.softmax()

softmax_output = F.softmax(tensor1,dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [52]:
#Initialize an embedding layer
vocab_size = 10000
embedding_size = 100
embedding = nn.Embedding(vocab_size,embedding_size)

#Create some input indices
input_indices = torch.LongTensor([1,5,3,2])

#Apply the embedding layer

embedding_output = embedding(input_indices)

#The output will be a tensor of shape (4,100), where 4 is the number of inputs 
# and 100 is the dimensionality of the embedding vectors
print(embedding_output.shape)
print(embedding_output)

torch.Size([4, 100])
tensor([[ 0.6446, -1.2023,  0.2470,  0.9962, -0.3906, -1.2739,  1.5316, -0.3540,
          0.2402,  2.2202, -1.7673,  0.5336, -1.0894,  1.2228, -0.5977,  0.0377,
         -1.5680,  1.4785,  0.4313, -0.3163,  0.2561, -0.1729, -0.6979, -0.2281,
         -0.2898,  0.9675,  0.0491,  0.1670,  0.9842, -0.9534, -0.7511,  0.7358,
          0.3900,  0.6773, -1.1108,  0.0448, -0.7375,  1.1513, -2.0618,  0.6190,
         -0.4195, -0.4554, -0.0701,  0.3244, -0.4174,  0.3046, -1.0003,  0.3314,
          0.0739,  2.4297, -0.9468,  0.1118,  0.6729,  0.1111,  1.7903, -0.3732,
         -0.6369, -0.5362,  0.0473, -0.4887, -2.8962, -0.1816,  1.0251,  0.3672,
         -1.0847,  0.5609, -0.0046,  0.3027, -0.2476, -1.5764,  1.2989, -1.7533,
          0.8058,  0.7911, -1.0334, -0.6080,  0.6673, -1.1430, -1.4847, -0.9277,
         -0.7685, -0.0603, -0.6127, -1.1851, -0.4055, -1.0543,  0.3554,  0.9435,
         -1.3110,  1.8552, -0.0863, -0.7980, -0.4355,  0.0976,  0.6385,  2.2463,
       

In [59]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a@b)
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [60]:
int_64 = torch.randint(1,(3,2))
#type int64
print(int_64)
float_32 = torch.rand((2,3))
print(float_32)
#type float32
print(int_64.dtype,float_32.dtype)
result = torch.matmul(int_64,float_32)
print(result)

tensor([[0, 0],
        [0, 0],
        [0, 0]])
tensor([[0.1518, 0.1893, 0.2554],
        [0.0546, 0.8495, 0.6651]])
torch.int64 torch.float32


RuntimeError: expected m1 and m2 to have the same dtype, but got: long long != float

In [61]:
int_64 = torch.randint(1,(3,2)).float()
#type int64
print(int_64)
float_32 = torch.rand((2,3))
print(float_32)
#type float32
print(int_64.dtype,float_32.dtype)
result = torch.matmul(int_64,float_32)
print(result)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.9134, 0.8545, 0.1169],
        [0.1561, 0.6222, 0.5028]])
torch.float32 torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [63]:
a = torch.rand(2,3,5)
print(a.shape)
x,y,z = a.shape
a = a.view(x,y,z)
print(a.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


In [65]:
input = torch.rand((4,8,10))
B,T,C = input.shape
output = input.view(B*T,C)
print(output)
print(output[:,-1,:])

tensor([[7.7274e-01, 5.1927e-01, 2.3079e-02, 7.0119e-01, 8.4227e-01, 5.8001e-01,
         3.8613e-01, 2.7344e-02, 1.0269e-01, 5.4072e-01],
        [3.7748e-01, 8.6957e-01, 6.6145e-01, 1.4624e-01, 9.4165e-01, 6.9688e-01,
         2.7833e-01, 7.6292e-01, 9.4740e-01, 8.5561e-01],
        [7.3350e-02, 9.9356e-01, 6.3588e-01, 4.1258e-01, 9.2029e-01, 7.1816e-01,
         1.0334e-01, 7.5096e-01, 5.7633e-01, 6.6898e-01],
        [7.3458e-01, 4.2309e-01, 6.9030e-01, 5.8263e-01, 9.7460e-01, 5.1472e-01,
         3.9184e-01, 6.0180e-01, 8.6680e-01, 3.9538e-01],
        [1.6883e-01, 9.0000e-01, 5.4538e-01, 5.6999e-02, 3.0914e-01, 9.0053e-01,
         8.6174e-01, 7.5022e-01, 1.5762e-01, 7.5337e-01],
        [6.5698e-01, 7.4356e-01, 4.3574e-01, 6.9732e-01, 9.0282e-01, 5.9390e-01,
         3.7369e-02, 7.3659e-01, 1.8234e-01, 2.9853e-01],
        [3.7473e-01, 5.0335e-01, 5.1399e-01, 9.2097e-01, 4.6752e-02, 8.8384e-01,
         1.7704e-02, 7.6470e-02, 5.8032e-01, 4.7645e-01],
        [8.5389e-01, 9.9617

IndexError: too many indices for tensor of dimension 2

In [68]:
x = torch.tensor([0.05],dtype=torch.float32)
y = F.relu(x)
print(y)

tensor([0.0500])


In [69]:
x = torch.tensor([-0.05],dtype=torch.float32)
y = F.sigmoid(x)
print(y)

tensor([0.4875])


In [70]:
x = torch.tensor([-0.05],dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([-0.0500])


In [71]:
x = torch.tensor([1],dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([0.7616])
